<?php
/**
 * Declare what blocks are provided by this module.
 * Implements hook_block_info().
 */
function app_seo_block_info(){
    $block['seo_application'] = array(
        'info' => t('Aplication SEO for Drupal by Orbelink'),
        'cache' => DRUPAL_NO_CACHE,
    );

    $block['calc_application'] = array(
        'info' => t('Aplication for calculate the responsiveness'),
        'cache' => DRUPAL_NO_CACHE,
    );

    return $block;
}
 
/**
 * Define what our block is going to look like.
 * Implements hook_block_view().
 */
function app_seo_block_view($block_key){
    $block = array();
 
    if($block_key == 'seo_application'){ //We only want to define the content of OUR block
        //This is the title of the block.
        $block['subject'] = "";
 
        //Define the block content.
        $block['content'] = '<div id="formulario-seo-contenido"><div class="bloque-encabezado-construimos-sueno">
                                <div class="bloque-encabezado-construimos-sueno-inner">
                                <h2>CALIFIQUE LA POSICIÓN DE SU SITIO EN GOOGLE</h2>
                                </div>
                                </div>
                                <div id="formulario-seo-contenedor">
                                    <div id="formulario-seo-contenedor-inner">
                                        <form action="#" method="post" id="formulario-seo">
                                        <div class="formulario-seo-inner">
                                                <div class="input-web-wrapper input-type-text">
                                                    <input type="text" name="miweb" id="miweb" placeholder="Escriba aquí la dirección de su sitio web"/>
                                                </div>
                                                <div class="input-termino-wrapper input-type-text">
                                                    <a id="hover-palabra-clave" href="javascript:void(0);"></a>
                                                    <input type="text" name="q" id="q" placeholder="Palabra clave" />
                                                    <div class="mensaje-palabra-clave"><div class="mensaje-palabra-clave-wrapper"><div class="mensaje-palabra-clave-flecha"></div><p>La Palabra clave se refiere al término con el cual buscaría usted su sitio web en google para saber en que posición se ubica. Por ejemplo, si su página es sobre un hotel en Guanacaste, entonces una palabra o frase clave podría ser: "Hotel Guanacaste"</p></div></div>
                                                </div>
                                                <div class="input-idioma-wrapper">
                                                    <div class="input-radio-espa">
                                                        <div class="input-radio-idioma-wrapper radio-activado">
                                                            <input type="radio" name="idioma" value="es_CR" checked="checked" />
                                                        </div> Español 
                                                    </div>
                                                    <div class="input-radio-eng">
                                                        <div class="input-radio-idioma-wrapper radio-desactivado">
                                                            <input type="radio" name="idioma" value="en_US" />
                                                        </div> Inglés 
                                                    </div>
                                                </div>
                                                <div class="input-google-wrapper">
                                                    <div class="input-radio-cr">
                                                        <div class="input-radio-google-wrapper radio-activado">
                                                            <input type="radio" name="bot" value="cr" checked="checked" />
                                                        </div> Google.co.cr</div>
                                                    <div class="input-radio-global">
                                                        <div class="input-radio-google-wrapper radio-desactivado">
                                                            <input type="radio" name="bot" value="0" />
                                                        </div> Google.com 
                                                     </div>
                                                </div>
                                               
                                                
                                                <div class="buscar-button-box"><a href="javascript:void(0);" id="consulta-seo">Buscar</a></div>
                                            </div>

                                           <div id="resultado-seo"></div>
                                    </form>
                                </div>
                            </div>
                            </div>';

    } else if ($block_key == 'calc_application') {
        //This is the title of the block.
        $block['subject'] = "";
 
        //Define the block content.
        $block['content'] = '<div id="block-app-seo-calc-application-inner"><form id="formulario-calc" action="#" method="post">
                            <h2>CALIFIQUE LA RESPONSIVIDAD DE SU SITIO</h2>
                                <div class="form-content">
                                    <input type="text" name="miweb" onkeypress="javascript:void();" id="miweb" placeholder="Escriba aquí la dirección de su sitio web"/>
                                    <a href="javascript:void(0);" id="consulta-calc"></a>
                                </div>
                            </form></div>
                            <div id="resultado-calc">
                                <div id="encabezado-calc"></div>
                                <div id="contenedor-iframe-calc">    
                                </div>
                                <div id="barra-vertical-calc"></div>
                            </div>';
    }
 
    return $block;
}

/**
 * 
 *  Implements hook_menu().
 *
 */

function app_seo_menu() {
    $items['consulta-seo'] = array(
      'page callback' => 'app_seo_view',
      'access arguments' => array('access content'),
    );

    $items['consulta-calc'] = array(
      'page callback' => 'app_calc_view',
      'access arguments' => array('access content'),
    );
    return $items;
  }

function app_seo_view() {
    if(isset($_POST['q']) and $_POST['q']!=""){
        
        $miweb = $_POST['miweb'];
        
        $q = $_POST['q'];
        $q = urlencode($q);
        $q = str_replace(" ", "+", $q);
        
        buscar($q,$miweb);
    }
  }

function app_calc_view() {
        
        calificar();
  }

function buscar($aQue,$web){
    $aUrl = "http://ajax.googleapis.com/ajax/services/search/web";
    $posicion = 0;
    $break = 0;
    $bot = '';
    if($_POST['bot'] != 0){ $bot = '&gl='.$_POST['bot'];}
    
    for($e=1;$e<=12;$e++){
    $data = file_get_contents($aUrl."?v=1.0&rsz=large".$bot."&hl=".$_POST['idioma']."&userip=192.165.0.12&start=".$posicion."&q=".$aQue); // Obtenemos el resultado
    $obj = json_decode($data); // Decodificamos el Json

    $results = $obj->responseData->results; // Entramos al array de los resultados

    for ($i=0; $i<sizeof($results); $i++) {
        $posicion = $posicion + 1;
        $tmp = $results[$i]; 
        //echo "POSICIÓN:" . $posicion . "<br />";
        
        flush(); ob_flush(); sleep(3);
        
        if(strpos($tmp->url, $web)){
            //echo "Se encuentra en la posición: <strong>" . $posicion . "</strong>, para el termino <strong>" . $_POST['q'] ."</strong>";
            print "{\"estatus\":1,\"posicion\":".$posicion.",\"termino\":\"".$_POST['q']."\"}";
            $break = 1;
            break;
        } elseif ($posicion == 31){
            print "{\"estatus\":0}";
            $break = 1;
            break;
        }
    }
    if($break==1){ break; }
    
    }
}


function calificar(){

    $score_viewport = 0;
    $google_score = 0;
    $mediaqueries_score = 0;
    $mediaqueries_score_2 = 0;

    if(isset($_POST['miweb']) and $_POST['miweb'] != ""){

    $data = file_get_contents("https://www.googleapis.com/pagespeedonline/v1/runPagespeed?url=".$_POST['miweb']."&locale=es_ES&strategy=mobile&key=AIzaSyCT_m7t-NebK-7yuIhS9v7KBGL_dpsdt-8");
    $obj = json_decode($data); 
    //echo $obj->score . "<br />";
    $google_score = (($obj->score)*100)/50;  
        
        $html = file_get_contents($_POST['miweb']);
        
        if(strpos($html, 'viewport')){
            $score_viewport = 30;
        }
        
        $array_media = array(
        'all and',
        'orientation',
        'device',
        'handheld and',
        'screen and',
        '@media',
        'only screen');
        if($a = strposa($html, $array_media)){
            $mediaqueries_score = 10;
        }

        $html = str_replace("'", "\"", $html);
        preg_match_all("/href=\"(.*\.(css?(.*?))+)\"/i",$html,$salida);
        preg_match_all("/@import url\(\"(.*\.(css?(.*?))+)\"\)/i",$html,$salida2);
        for($e = 0; $e < count($salida2[1]); $e++){
            $salida[1][] = $salida2[1][$e];
        }           
        $counnt = count($salida[1]);
        for($i = 0; $i < count($salida[1]); $i++){
            $css = file_get_contents(addhttp($salida[1][$i],1));
            if($a = strposa($css, $array_media)){
                 $mediaqueries_score_2 = 10;
            }
        }               

        print "{\"score\":"+ $obj->score +",\"viewport_score\":"+ $score_viewport +",\"mediaqueries_score\":"+ $mediaqueries_score+$mediaqueries_score_2 +"}";
        
    }
}

function addhttp($url,$css=0){
    if($css == 'css'){
        $res = preg_match('@(www\.|http://)([^\s]*)@i', $_POST['miweb'], $link);
        $url = $link[0] . "/" . $url;
    }
    if (false === strpos($url, '://')) {
        return 'http://' . $url;
    }
    return $url;
}

function strposa($haystack, $needle, $offset=0) {
    if(!is_array($needle)) $needle = array($needle);
    $k = array();
    foreach($needle as $query) {
        if(strpos($haystack, $query, $offset) !== false) $k[] = $query;
    }
    if(count($k)>0){ return $k; }
    return false;
}