<?php
/**
 * Declare what blocks are provided by this module.
 * Implements hook_block_info().
 */
function app_seo_block_info(){
    $block['seo_application'] = array(
        'info' => t('Aplication SEO for Drupal by Orbelink'),
        'cache' => DRUPAL_NO_CACHE,
    );

    $block['calc_application'] = array(
        'info' => t('Aplication for calculate the responsiveness'),
        'cache' => DRUPAL_NO_CACHE,
    );

    return $block;
}
 
/**
 * Define what our block is going to look like.
 * Implements hook_block_view().
 */
function app_seo_block_view($block_key){
    $block = array();
 
    if($block_key == 'seo_application'){ //We only want to define the content of OUR block
        //This is the title of the block.
        $block['subject'] = "";
 
        //Define the block content.
        $block['content'] = '<div id="formulario-seo-contenido"><div class="bloque-encabezado-construimos-sueno">
                                <div class="bloque-encabezado-construimos-sueno-inner">
                                <h2>CALIFIQUE LA POSICIÓN DE SU SITIO EN GOOGLE</h2>
                                </div>
                                </div>
                                <div id="formulario-seo-contenedor">
                                    <div id="formulario-seo-contenedor-inner">
                                        <form action="#" method="post" id="formulario-seo">
                                        <div class="formulario-seo-inner">
                                                <div class="input-web-wrapper input-type-text">
                                                    <input type="text" name="miweb" id="miweb" placeholder="Escriba aquí la dirección de su sitio web"/>
                                                </div>
                                                <div class="input-termino-wrapper input-type-text">
                                                    <a id="hover-palabra-clave" href="javascript:void(0);"></a>
                                                    <input type="text" name="q" id="q" placeholder="Palabra clave" />
                                                    <div class="mensaje-palabra-clave"><div class="mensaje-palabra-clave-wrapper"><div class="mensaje-palabra-clave-flecha"></div><p>La Palabra clave se refiere al término con el cual buscaría usted su sitio web en google para saber en que posición se ubica. Por ejemplo, si su página es sobre un hotel en Guanacaste, entonces una palabra o frase clave podría ser: "Hotel Guanacaste"</p></div></div>
                                                </div>
                                                <div class="input-idioma-wrapper">
                                                    <div class="input-radio-espa">
                                                        <div class="input-radio-idioma-wrapper radio-activado">
                                                            <input type="radio" name="idioma" value="es_CR" checked="checked" />
                                                        </div> Español 
                                                    </div>
                                                    <div class="input-radio-eng">
                                                        <div class="input-radio-idioma-wrapper radio-desactivado">
                                                            <input type="radio" name="idioma" value="en_US" />
                                                        </div> Inglés 
                                                    </div>
                                                </div>
                                                <div class="input-google-wrapper">
                                                    <div class="input-radio-cr">
                                                        <div class="input-radio-google-wrapper radio-activado">
                                                            <input type="radio" name="bot" value="cr" checked="checked" />
                                                        </div> Google.co.cr</div>
                                                    <div class="input-radio-global">
                                                        <div class="input-radio-google-wrapper radio-desactivado">
                                                            <input type="radio" name="bot" value="0" />
                                                        </div> Google.com 
                                                     </div>
                                                </div>
                                               
                                                
                                                <div class="buscar-button-box"><a href="javascript:void(0);" id="consulta-seo">Buscar</a></div>
                                            </div>

                                           <div id="resultado-seo"></div>
                                    </form>
                                </div>
                            </div>
                            </div>';

    } else if ($block_key == 'calc_application') {
        //This is the title of the block.
        $block['subject'] = "";
 
        //Define the block content.
        $block['content'] = '<div class="block-app-seo-wrapper">
		<div id="block-app-seo-calc-application-inner"><form id="formulario-calc" action="#" method="post">
        <h2>CALIFIQUE LA RESPONSIVIDAD DE SU SITIO</h2>
                                <div class="form-content">
                                    <input type="text" name="miweb" onkeypress="javascript:void();" id="miweb" placeholder="Escriba aquí la dirección de su sitio web"/>
                                    <a href="javascript:void(0);" id="consulta-calc"></a>
                                </div>
                            </form></div></div>
							



							
							
							
                            <div id="resultado-calc">

<div class="row r1">
	<div id="encabezado-calc"></div>
	<div id="contenedor-iframe-calc"></div>
</div>
<div class="row r2">
	
	

<table width="100%" border="0" class="reporte_d">
  <tr>
    <td colspan="3"><div id="top" style="background-image: url(/sites/all/themes/orbelink/images/cara-dudosa-diseno-web.png);"></div></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>Ventana gráfica:</td>
    <td>0000</td>
    <td>%</td>
  </tr>
  <tr>
    <td>Velocidad de la web:</td>
    <td>0000</td>
    <td>%</td>
  </tr>
  <tr>
    <td>Tamaño de fuente:</td>
    <td>0000</td>
    <td>%</td>
  </tr>
  <tr>
    <td>Usabilidad tactil:</td>
    <td>0000</td>
    <td>%</td>
  </tr>
</table>


	
	
<!--	<div id="barra-vertical-calc">
	
	
	
	
	
	</div>-->
	
	
</div>
  
                            </div>
							
							
							
							';
    }
 
    return $block;
}

/**
 * 
 *  Implements hook_menu().
 *
 */

function app_seo_menu()
{
    $items['consulta-seo'] = array(
      'page callback' => 'app_seo_view',
      'access arguments' => array('access content'),
    );

    $items['consulta-calc'] = array(
      'page callback' => 'app_calc_view',
      'access arguments' => array('access content'),
    );
    return $items;
  }

function app_seo_view()
{
    if(isset($_POST['q']) and $_POST['q']!=""){
        
        $miweb = $_POST['miweb'];
        
        $q = $_POST['q'];
        $q = urlencode($q);
        $q = str_replace(" ", "+", $q);
        
        buscar($q,$miweb);
    }
  }

function app_calc_view()
{
        
        calificar();
  }

function getIp()
{
	if(!empty($_SERVER['HTTP_CLIENT_IP'])) {
		return $_SERVER['HTTP_CLIENT_IP'];
	} elseif(!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
		return $_SERVER['HTTP_X_FORWARDED_FOR'];
	} else {
		return $_SERVER['REMOTE_ADDR'];
	}}

function buscar($aQue,$web)
{
    $aUrl = "http://ajax.googleapis.com/ajax/services/search/web";
    $posicion = 0;
    $break = 0;
    $bot = '';
    if($_POST['bot'] != 0){ $bot = '&gl='.$_POST['bot'];}
    
    for($e=1;$e<=12;$e++){
    $data = file_get_contents($aUrl."?v=1.0&rsz=large".$bot."&hl=".$_POST['idioma']."&userip=".getIp()."&start=".$posicion."&q=".$aQue); // Obtenemos el resultado
    $obj = json_decode($data); // Decodificamos el Json

    $results = $obj->responseData->results; // Entramos al array de los resultados

    for ($i=0; $i<sizeof($results); $i++) {
        $posicion = $posicion + 1;
        $tmp = $results[$i]; 
        //echo "POSICIÓN:" . $posicion . "<br />";
        
        flush(); ob_flush(); sleep(3);
        
		$pos = strpos($tmp->url, addhttp($web));
		if($pos !== false){
            //echo "Se encuentra en la posición: <strong>" . $posicion . "</strong>, para el termino <strong>" . $_POST['q'] ."</strong>";
            print "{\"estatus\":1,\"posicion\":".$posicion.",\"termino\":\"".$_POST['q']."\"}";
            $break = 1;
            break;
        } elseif ($posicion == 30){
            print "{\"estatus\":0}";
            $break = 1;
            break;
        }
    }
    if($break==1){ break; }
    
    }}


function calificar(){

    if(isset($_POST['miweb']) and $_POST['miweb'] != ""){
    	$web = addhttp($_POST['miweb']);
        $url = "https://www.googleapis.com/pagespeedonline/v1/runPagespeed?url=".$web."&locale=es_ES&strategy=mobile&key=AIzaSyBEI5SY3n4oRzk76cz1J1sYHVwf2USRW_w";
      // Create the stream context, we solve the issue for hung and waitting
                $context = stream_context_create(array(
                    'http' => array(
                    'timeout' => 2      // Timeout in seconds
                    )
                ));

       $data = @file_get_contents($url, 0, $context);

       $obj = json_decode($data);
       //print_r($obj->formattedResults->ruleResults->SizeContentToViewport->ruleImpact); 
       
       //2. velocidad
       $impactoVelocidad = $obj->score;

       $porcentajesimpactoVelocidad = calcularVelocidad($impactoVelocidad, 30);
       $porcentajeIndividualimpactoVelocidad = $porcentajesimpactoVelocidad['porcentajeImpactoIndividual'];
       //$porcentajeGrupalimpactoVelocidad = $porcentajesimpactoVelocidad['porcentajeImpactoGrupal'];

       $arrayVelocidad = array("impactoVelocidad" => array(
                                                    "porcentajeVelocidad" => $porcentajeIndividualimpactoVelocidad,
                                                    //"porcentajeGrupal" => $porcentajeGrupalimpactoVelocidad
                                                )
                               );

       // obtener el url a consultar
       $id = $obj->id;
       $arrayUrl = array("url" => $id);

       //obtener el array final y hacer un merge entre los arrays
       $datosImpactos = obtenerImpactos($obj->formattedResults->ruleResults);
       
       $datosImpactos = array_merge($datosImpactos, $arrayUrl);
       $datosImpactos = array_merge($datosImpactos, $arrayVelocidad);

       print_r(json_encode($datosImpactos));
            
    }
}

 //nuestro indicador para obtener los impactos se basan en los siguientes casos:
   //ADAPTACION (Size content to viewport): El contenido de tu página encaja con la ventana gráfica.
   //FUENTE (UseLegibleFontSizes): Si los tamaños de las tipografias son los adecuados segun dispositivo empleado
   //ANCHO WEB (): Como el sitio se adapta al ancho del dispositivo
 function obtenerImpactos($ruleResults){

    //extraer el impacto de cada una de las reglas empleados
    //1. SizeContentToViewport
    //importante verificar si tiene configurado el viewport
    //si lo tiene configurado, entonces se procede a extraer el impacto del size content to view port
    $porcentajeIndividualimpactoSizeContentToViewport = 0;
    $porcentajeGrupalimpactoSizeContentToViewport = 0;
    
    if($ruleResults->ConfigureViewport->ruleImpact != 10){
        //aplicar calculo
        $porcentajesimpactoSizeContentToViewport = calcularPorcentajeDeImpacto($ruleResults->SizeContentToViewport->ruleImpact, 50);
        $porcentajeIndividualimpactoSizeContentToViewport = $porcentajesimpactoSizeContentToViewport['porcentajeImpactoIndividual'];
        $porcentajeGrupalimpactoSizeContentToViewport = $porcentajesimpactoSizeContentToViewport['porcentajeImpactoGrupal'];
    }

    //3. UseLegibleFontSizes
    $porcentajesimpactoUseLegibleFontSizes = calcularPorcentajeDeImpacto($ruleResults->UseLegibleFontSizes->ruleImpact, 15);
    $porcentajeIndividualimpactoUseLegibleFontSizes = $porcentajesimpactoUseLegibleFontSizes['porcentajeImpactoIndividual'];
    $porcentajeGrupalimpactoUseLegibleFontSizes = $porcentajesimpactoUseLegibleFontSizes['porcentajeImpactoGrupal'];

    //4. SizeTapTargetsAppropriately
    $porcentajesimpactoSizeTapTargetsAppropriately = calcularPorcentajeDeImpacto($ruleResults->SizeTapTargetsAppropriately->ruleImpact, 5);
    $porcentajeIndividualimpactoSizeTapTargetsAppropriately = $porcentajesimpactoSizeTapTargetsAppropriately['porcentajeImpactoIndividual'];
    $porcentajeGrupalimpactoSizeTapTargetsAppropriately = $porcentajesimpactoSizeTapTargetsAppropriately['porcentajeImpactoGrupal'];

    return array(
            "impactoSizeContentToViewport" => array(
                                                "porcentajeIndividual" => $porcentajeIndividualimpactoSizeContentToViewport
                                            ),
            "impactoUseLegibleFontSizes" => array(
                                                "porcentajeIndividual" => $porcentajeIndividualimpactoUseLegibleFontSizes
                                            ),
            "SizeTapTargetsAppropriately" => array(
                                                "porcentajeIndividual" => $porcentajeIndividualimpactoSizeTapTargetsAppropriately
                                            ),
            "TotalPorcentajeGrupal" => array(
                                                "porcentajeGrupal" => $porcentajeGrupalimpactoSizeContentToViewport + $porcentajeGrupalimpactoUseLegibleFontSizes + $porcentajeGrupalimpactoSizeTapTargetsAppropriately
                                            )
            );
 }

function calcularPorcentajeDeImpacto($impacto, $porcentajeGrupal){

    $impacto = floor($impacto);

    if($impacto >= 10) {
        $porcentajeImpactoIndividual = 0;
        $porcentajeImpactoGrupal = 0;   
    } else if($impacto > 0) {
        $porcentajeImpactoIndividual = (10 - $impacto)*(100/10);
        $porcentajeImpactoGrupal = $porcentajeImpactoIndividual * ($porcentajeGrupal/100);
    }

    if($impacto == 0) {
        $porcentajeImpactoIndividual = 100; 
        $porcentajeImpactoGrupal = $porcentajeGrupal;
    }

    return array(
            "porcentajeImpactoIndividual" => $porcentajeImpactoIndividual,
            "porcentajeImpactoGrupal" => $porcentajeImpactoGrupal
        );

 }

 function calcularVelocidad($velocidad, $porcentajeGrupal){

    $velocidad = floor($velocidad);

        $porcentajeImpactoIndividual = ($velocidad * $porcentajeGrupal)/100;
        $porcentajeImpactoGrupal = $velocidad;

    return array(
            "porcentajeImpactoIndividual" => $porcentajeImpactoIndividual,
            "porcentajeImpactoGrupal" => $porcentajeImpactoGrupal
        );

 }

function addhttpVIEJA($url,$css=0){
    if($css == 'css'){
        $res = preg_match('@(www\.|http://)([^\s]*)@i', $_POST['miweb'], $link);
        $url = $link[0] . "/" . $url;
    }
    if (false === strpos($url, '://')) {
        return 'http://' . $url;
    }
    return $url;
}
function addhttp($url,$css=0){
	if($css == 1){
		
		$res = preg_match('@(www\.|http://)([^\s]*)@i', $url, $link);
		$url = $link[0];
		if (false === strpos($url, '://')) {
			$url = 'http://' . $url;
		}	
			
	}else{
	
		if (!preg_match("~^(?:f|ht)tps?://~i", $url)) {
			$url = "http://" . $url;
		}
	
	}
	return $url;
}

function strposa($haystack, $needle, $offset=0) {
    if(!is_array($needle)) $needle = array($needle);
    $k = array();
    foreach($needle as $query) {
        if(strpos($haystack, $query, $offset) !== false) $k[] = $query;
    }
    if(count($k)>0){ return $k; }
    return false;
}